name: ecomm_ai_py311          # Conda env name
channels:
  - conda-forge
  - defaults

dependencies:
  # Core Python
  - python=3.11

  # Data stack
  - pandas
  - numpy
  - scikit-learn
  - xgboost
  - lightgbm
  - lifetimes            # BG/NBD + Gamma-Gamma
  - duckdb

  # Orchestration & tracking
  - prefect              # Prefect 2
  - mlflow

  # DB clients & migrations
  - sqlalchemy
  - psycopg2             # Postgres driver
  - dbt-core
  - dbt-postgres

  # Quality & testing
  - great-expectations
  - pytest
  - mypy
  - black
  - ruff
  - pre-commit

  # Logging & env
  - loguru
  - python-dotenv

  # Notebook support
  - jupyter

  # fall-back pip installs
  - pip
  - pip:
      - evidently>=0.4.12
      - fastapi
      - uvicorn[standard]
      - plotly