# environment.yml
name: ecomm_ai_py311          # Conda env name
channels:
  - conda-forge
  - defaults

dependencies:
  # ── Core Python
  - python=3.11

  # ── Data & modeling
  - pandas
  - numpy
  - scikit-learn
  - xgboost
  - lightgbm
  - lifetimes            # BG/NBD + Gamma–Gamma
  - duckdb

  # ── Orchestration & tracking
  - prefect              # Prefect 2
  - mlflow

  # ── Database clients & migrations
  - sqlalchemy
  - psycopg2             # Postgres driver
  - dbt-core
  - dbt-postgres

  # ── Data quality & testing
  - great-expectations
  - pytest
  - mypy
  - black
  - ruff
  - pre-commit

  # ── Logging & environment variables
  - loguru
  - python-dotenv

  # ── Notebook support
  - jupyter

  # ── fall-back pip installs
  - pip
  - pip:
      - evidently>=0.4.12
      - fastapi
      - uvicorn[standard]
      - plotly