name: ecomm_ai_py311          # Conda env name
channels:
  - conda-forge               # always search here first
  - defaults

dependencies:
  # ── Core Python
  - python = 3.11

  # ── Data & modelling
  - pandas
  - numpy
  - scikit-learn
  - lightgbm
  - xgboost
  - lifetimes                # BG/NBD + Gamma–Gamma
  - duckdb

  # ── Visualisation / notebook helper
  - matplotlib
  - seaborn
  - ipywidgets               # interactive widgets
  - ipykernel                # so the env registers in Jupyter
  - joblib                   # parallel loops
  - tqdm                     # progress bars

  # ── Experiment tracking & orchestration
  - mlflow
  - prefect                  # Prefect 2

  # ── Database / data-ops
  - sqlalchemy
  - psycopg2                 # Postgres driver (dbt & Python)
  - dbt-core
  - dbt-postgres

  # ── Data quality / testing / linting
  - great-expectations
  - pytest
  - black
  - ruff
  - mypy
  - pre-commit

  # ── Logging & env vars
  - loguru
  - python-dotenv

  # ── OPTIONAL: Node + npm (for the React dashboard)
  #     Comment these two lines out if you prefer using nvm or system-wide Node.
  # - nodejs = 20

  # ── fallback PyPI installs
  - pip
  - pip:
      - kaggle                # dataset downloads
      - evidently>=0.4.12     # monitoring / drift
      - fastapi               # API serving
      - uvicorn[standard]     # ASGI server
      - plotly                # interactive graphs