services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: olist
      POSTGRES_PASSWORD: olist
      POSTGRES_DB: olist
    ports: ["5432:5432"]
    volumes: ["postgres_data:/var/lib/postgresql/data"]

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root ./mlruns
      --host 0.0.0.0
    ports: ["5000:5000"]
    volumes: ["./mlruns:/mlruns"]

  prefect:
    image: prefecthq/prefect:2-latest
    command: prefect server start --host 0.0.0.0
    ports: ["4200:4200"]

  grafana:
    image: grafana/grafana-oss:10.3.1
    ports: ["3000:3000"]

volumes:
  postgres_data: