name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: ecomm_ai_py311
          environment-file: environment.yml
          auto-activate-base: false
          python-version: 3.11

      - name: Install dev dependencies
        shell: bash -l {0}
        run: |
          pip install black ruff mypy pytest

      - name: Lint & type-check
        shell: bash -l {0}
        run: |
          black --check .
          ruff .
          mypy customer_ai/

      - name: Run unit tests
        shell: bash -l {0}
        run: |
          pytest -q